# Generated by Django 3.2.1 on 2021-05-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('S', 'Stock'), ('NS', 'No Stock')], default='Stock', max_length=2)),
            ],
        ),
    ]
