# Generated by Django 3.2.1 on 2021-05-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_category',
            field=models.CharField(choices=[('S', 'vehicles'), ('VF', 'Estate'), ('SC', 'Technology'), ('SC', 'Tools'), ('SC', 'Home Appliances'), ('SC', 'Construction'), ('SC', 'Sports'), ('SC', 'Toys'), ('SC', 'Fashion'), ('SC', 'Services')], default='', max_length=2),
        ),
    ]
