# Generated by Django 3.2.1 on 2021-05-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0002_product_p_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_category',
            new_name='product_category',
        ),
    ]
